# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand((7,7))
x

tensor([[0.4210, 0.1638, 0.7791, 0.4027, 0.0819, 0.0597, 0.1039],
        [0.0360, 0.4368, 0.2546, 0.8696, 0.0404, 0.4529, 0.2798],
        [0.4084, 0.0826, 0.5266, 0.8150, 0.7740, 0.3043, 0.7418],
        [0.5891, 0.0237, 0.1225, 0.3045, 0.4188, 0.5577, 0.1507],
        [0.2791, 0.7750, 0.9471, 0.7519, 0.3535, 0.9101, 0.0450],
        [0.5016, 0.4577, 0.9212, 0.8111, 0.0017, 0.0997, 0.8754],
        [0.4931, 0.6595, 0.4983, 0.3974, 0.4187, 0.3353, 0.1170]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
y = torch.rand(1,7).transpose(0,1)
# Perform matrix multiplication 
z = torch.matmul(x,y)
z

tensor([[0.7297],
        [0.6350],
        [1.0212],
        [0.7738],
        [1.3421],
        [1.2234],
        [0.9299]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(1234)

# Create two random tensors
x1 = torch.rand(7,7)
torch.manual_seed(1234)
x2 = torch.rand(7,7)
print(x1)
print(x2)
# Matrix multiply tensors
z1 = torch.matmul(x1,x2)
print(z1)

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]])
tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]])
tensor([[0.9155, 1.1862, 0.7983, 1.5767, 0.6830, 0.9973, 0.7394],
        

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
x2 = torch.rand(2,3, device="cuda:0")
torch.cuda.manual_seed(1234)
y2 = torch.rand(2,3, device="cuda:0")
print(x2)
print(y2)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [36]:
# Perform matmul on tensor_A and tensor_B
z2 = torch.matmul(x2,y2.transpose(0,1))
z2

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [38]:
# Find max
z2.max()
# Find min
z2.min()

tensor(0.8358, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [40]:
# Find arg max
z2.argmax()

# Find arg min
z2.argmin()

tensor(1, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [50]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t3 = torch.rand(2,2,2,10)

# Remove single dimensions
t3 = t3.squeeze()
print(t3, t3.shape)
t3 = t3.squeeze()
print(t3, t3.shape)
t3 = t3.squeeze()
print(t3, t3.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513],
          [0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204, 0.0731,
           0.9699, 0.1078]],

         [[0.8829, 0.4132, 0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286,
           0.7653, 0.1132],
          [0.8559, 0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214,
           0.3742, 0.1953]]],


        [[[0.7405, 0.2529, 0.2332, 0.9314, 0.9575, 0.5575, 0.4134, 0.4355,
           0.7369, 0.0331],
          [0.0914, 0.8994, 0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990,
           0.7447, 0.7213]],

         [[0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196, 0.2147, 0.2816,
           0.6679, 0.7878],
          [0.5070, 0.3055, 0.7738, 0.2259, 0.3826, 0.9717, 0.5921, 0.5352,
           0.6686, 0.3781]]]]) torch.Size([2, 2, 2, 10])
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513],
          [0.8549, 0.5509, 0.2868, 0